window.esdocSearchIndex = [
  [
    "@ignavia/rdf/src/blanknode.js~blanknode",
    "class/src/BlankNode.js~BlankNode.html",
    "<span>BlankNode</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/BlankNode.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/graph.js~graph",
    "class/src/Graph.js~Graph.html",
    "<span>Graph</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/Graph.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/literal.js~literal",
    "class/src/Literal.js~Literal.html",
    "<span>Literal</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/Literal.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/n3/n3lexer.js~n3lexer",
    "function/index.html#static-function-N3Lexer",
    "<span>N3Lexer</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/n3/n3Lexer.js</span>",
    "function"
  ],
  [
    "@ignavia/rdf/src/n3/n3parser.js~n3parser",
    "function/index.html#static-function-N3Parser",
    "<span>N3Parser</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/n3/n3Parser.js</span>",
    "function"
  ],
  [
    "@ignavia/rdf/src/namednode.js~namednode",
    "class/src/NamedNode.js~NamedNode.html",
    "<span>NamedNode</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/NamedNode.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/prefixmap.js~prefixmap",
    "class/src/PrefixMap.js~PrefixMap.html",
    "<span>PrefixMap</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/PrefixMap.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/profile.js~profile",
    "class/src/Profile.js~Profile.html",
    "<span>Profile</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/Profile.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/rdfenvironment.js~rdfenvironment",
    "class/src/RDFEnvironment.js~RDFEnvironment.html",
    "<span>RDFEnvironment</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/RDFEnvironment.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/rdfnode.js~rdfnode",
    "class/src/RDFNode.js~RDFNode.html",
    "<span>RDFNode</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/RDFNode.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/termmap.js~termmap",
    "class/src/TermMap.js~TermMap.html",
    "<span>TermMap</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/TermMap.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/triple.js~triple",
    "class/src/Triple.js~Triple.html",
    "<span>Triple</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/Triple.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/turtlereader.js~turtlereader",
    "class/src/TurtleReader.js~TurtleReader.html",
    "<span>TurtleReader</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/TurtleReader.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/turtlewriter.js~turtlewriter",
    "class/src/TurtleWriter.js~TurtleWriter.html",
    "<span>TurtleWriter</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/TurtleWriter.js</span>",
    "class"
  ],
  [
    "@ignavia/rdf/src/xmlschematypes.js~xmlschematypes",
    "variable/index.html#static-variable-xmlSchemaTypes",
    "<span>xmlSchemaTypes</span> <span class=\"search-result-import-path\">@ignavia/rdf/src/xmlSchemaTypes.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/blanknode.js",
    "file/src/BlankNode.js.html",
    "src/BlankNode.js",
    "file"
  ],
  [
    "src/blanknode.js~blanknode#constructor",
    "class/src/BlankNode.js~BlankNode.html#instance-constructor-constructor",
    "src/BlankNode.js~BlankNode#constructor",
    "method"
  ],
  [
    "src/blanknode.js~blanknode#equals",
    "class/src/BlankNode.js~BlankNode.html#instance-method-equals",
    "src/BlankNode.js~BlankNode#equals",
    "method"
  ],
  [
    "src/blanknode.js~blanknode#tempname",
    "class/src/BlankNode.js~BlankNode.html#instance-get-tempName",
    "src/BlankNode.js~BlankNode#tempName",
    "member"
  ],
  [
    "src/blanknode.js~blanknode#tont",
    "class/src/BlankNode.js~BlankNode.html#instance-method-toNT",
    "src/BlankNode.js~BlankNode#toNT",
    "method"
  ],
  [
    "src/blanknode.js~blanknode#tostring",
    "class/src/BlankNode.js~BlankNode.html#instance-method-toString",
    "src/BlankNode.js~BlankNode#toString",
    "method"
  ],
  [
    "src/blanknode.js~blanknode#valueof",
    "class/src/BlankNode.js~BlankNode.html#instance-method-valueOf",
    "src/BlankNode.js~BlankNode#valueOf",
    "method"
  ],
  [
    "src/blanknode.js~blanknode.fromnt",
    "class/src/BlankNode.js~BlankNode.html#static-method-fromNT",
    "src/BlankNode.js~BlankNode.fromNT",
    "method"
  ],
  [
    "src/blanknode.js~blanknode.isntblanknode",
    "class/src/BlankNode.js~BlankNode.html#static-method-isNTBlankNode",
    "src/BlankNode.js~BlankNode.isNTBlankNode",
    "method"
  ],
  [
    "src/graph.js",
    "file/src/Graph.js.html",
    "src/Graph.js",
    "file"
  ],
  [
    "src/graph.js~graph#[symbol.iterator]",
    "class/src/Graph.js~Graph.html#instance-method-[Symbol.iterator]",
    "src/Graph.js~Graph#[Symbol.iterator]",
    "method"
  ],
  [
    "src/graph.js~graph#add",
    "class/src/Graph.js~Graph.html#instance-method-add",
    "src/Graph.js~Graph#add",
    "method"
  ],
  [
    "src/graph.js~graph#addall",
    "class/src/Graph.js~Graph.html#instance-method-addAll",
    "src/Graph.js~Graph#addAll",
    "method"
  ],
  [
    "src/graph.js~graph#addnodetoidmap",
    "class/src/Graph.js~Graph.html#instance-method-addNodeToIdMap",
    "src/Graph.js~Graph#addNodeToIdMap",
    "method"
  ],
  [
    "src/graph.js~graph#clear",
    "class/src/Graph.js~Graph.html#instance-method-clear",
    "src/Graph.js~Graph#clear",
    "method"
  ],
  [
    "src/graph.js~graph#constructor",
    "class/src/Graph.js~Graph.html#instance-constructor-constructor",
    "src/Graph.js~Graph#constructor",
    "method"
  ],
  [
    "src/graph.js~graph#every",
    "class/src/Graph.js~Graph.html#instance-method-every",
    "src/Graph.js~Graph#every",
    "method"
  ],
  [
    "src/graph.js~graph#filter",
    "class/src/Graph.js~Graph.html#instance-method-filter",
    "src/Graph.js~Graph#filter",
    "method"
  ],
  [
    "src/graph.js~graph#foreach",
    "class/src/Graph.js~Graph.html#instance-method-forEach",
    "src/Graph.js~Graph#forEach",
    "method"
  ],
  [
    "src/graph.js~graph#getnodebyid",
    "class/src/Graph.js~Graph.html#instance-method-getNodeById",
    "src/Graph.js~Graph#getNodeById",
    "method"
  ],
  [
    "src/graph.js~graph#gettriplebyid",
    "class/src/Graph.js~Graph.html#instance-method-getTripleById",
    "src/Graph.js~Graph#getTripleById",
    "method"
  ],
  [
    "src/graph.js~graph#hasnode",
    "class/src/Graph.js~Graph.html#instance-method-hasNode",
    "src/Graph.js~Graph#hasNode",
    "method"
  ],
  [
    "src/graph.js~graph#hastriple",
    "class/src/Graph.js~Graph.html#instance-method-hasTriple",
    "src/Graph.js~Graph#hasTriple",
    "method"
  ],
  [
    "src/graph.js~graph#id",
    "class/src/Graph.js~Graph.html#instance-member-id",
    "src/Graph.js~Graph#id",
    "member"
  ],
  [
    "src/graph.js~graph#iterequivalentnodes",
    "class/src/Graph.js~Graph.html#instance-method-iterEquivalentNodes",
    "src/Graph.js~Graph#iterEquivalentNodes",
    "method"
  ],
  [
    "src/graph.js~graph#iterequivalenttriples",
    "class/src/Graph.js~Graph.html#instance-method-iterEquivalentTriples",
    "src/Graph.js~Graph#iterEquivalentTriples",
    "method"
  ],
  [
    "src/graph.js~graph#iternodes",
    "class/src/Graph.js~Graph.html#instance-method-iterNodes",
    "src/Graph.js~Graph#iterNodes",
    "method"
  ],
  [
    "src/graph.js~graph#length",
    "class/src/Graph.js~Graph.html#instance-get-length",
    "src/Graph.js~Graph#length",
    "member"
  ],
  [
    "src/graph.js~graph#literals",
    "class/src/Graph.js~Graph.html#instance-method-literals",
    "src/Graph.js~Graph#literals",
    "method"
  ],
  [
    "src/graph.js~graph#match",
    "class/src/Graph.js~Graph.html#instance-method-match",
    "src/Graph.js~Graph#match",
    "method"
  ],
  [
    "src/graph.js~graph#merge",
    "class/src/Graph.js~Graph.html#instance-method-merge",
    "src/Graph.js~Graph#merge",
    "method"
  ],
  [
    "src/graph.js~graph#objects",
    "class/src/Graph.js~Graph.html#instance-method-objects",
    "src/Graph.js~Graph#objects",
    "method"
  ],
  [
    "src/graph.js~graph#predicatehasliterals",
    "class/src/Graph.js~Graph.html#instance-method-predicateHasLiterals",
    "src/Graph.js~Graph#predicateHasLiterals",
    "method"
  ],
  [
    "src/graph.js~graph#predicates",
    "class/src/Graph.js~Graph.html#instance-method-predicates",
    "src/Graph.js~Graph#predicates",
    "method"
  ],
  [
    "src/graph.js~graph#remove",
    "class/src/Graph.js~Graph.html#instance-method-remove",
    "src/Graph.js~Graph#remove",
    "method"
  ],
  [
    "src/graph.js~graph#removematches",
    "class/src/Graph.js~Graph.html#instance-method-removeMatches",
    "src/Graph.js~Graph#removeMatches",
    "method"
  ],
  [
    "src/graph.js~graph#some",
    "class/src/Graph.js~Graph.html#instance-method-some",
    "src/Graph.js~Graph#some",
    "method"
  ],
  [
    "src/graph.js~graph#subjecthasliterals",
    "class/src/Graph.js~Graph.html#instance-method-subjectHasLiterals",
    "src/Graph.js~Graph#subjectHasLiterals",
    "method"
  ],
  [
    "src/graph.js~graph#subjects",
    "class/src/Graph.js~Graph.html#instance-method-subjects",
    "src/Graph.js~Graph#subjects",
    "method"
  ],
  [
    "src/graph.js~graph#toarray",
    "class/src/Graph.js~Graph.html#instance-method-toArray",
    "src/Graph.js~Graph#toArray",
    "method"
  ],
  [
    "src/graph.js~graph#tonodeobj",
    "class/src/Graph.js~Graph.html#instance-method-toNodeObj",
    "src/Graph.js~Graph#toNodeObj",
    "method"
  ],
  [
    "src/graph.js~graph#tostring",
    "class/src/Graph.js~Graph.html#instance-method-toString",
    "src/Graph.js~Graph#toString",
    "method"
  ],
  [
    "src/graph.js~graph#totripleobj",
    "class/src/Graph.js~Graph.html#instance-method-toTripleObj",
    "src/Graph.js~Graph#toTripleObj",
    "method"
  ],
  [
    "src/graph.js~graph.tonodeid",
    "class/src/Graph.js~Graph.html#static-method-toNodeId",
    "src/Graph.js~Graph.toNodeId",
    "method"
  ],
  [
    "src/graph.js~graph.totripleid",
    "class/src/Graph.js~Graph.html#static-method-toTripleId",
    "src/Graph.js~Graph.toTripleId",
    "method"
  ],
  [
    "src/literal.js",
    "file/src/Literal.js.html",
    "src/Literal.js",
    "file"
  ],
  [
    "src/literal.js~literal#[symbol.toprimitive]",
    "class/src/Literal.js~Literal.html#instance-method-[Symbol.toPrimitive]",
    "src/Literal.js~Literal#[Symbol.toPrimitive]",
    "method"
  ],
  [
    "src/literal.js~literal#constructor",
    "class/src/Literal.js~Literal.html#instance-constructor-constructor",
    "src/Literal.js~Literal#constructor",
    "method"
  ],
  [
    "src/literal.js~literal#datatype",
    "class/src/Literal.js~Literal.html#instance-member-datatype",
    "src/Literal.js~Literal#datatype",
    "member"
  ],
  [
    "src/literal.js~literal#equals",
    "class/src/Literal.js~Literal.html#instance-method-equals",
    "src/Literal.js~Literal#equals",
    "method"
  ],
  [
    "src/literal.js~literal#language",
    "class/src/Literal.js~Literal.html#instance-member-language",
    "src/Literal.js~Literal#language",
    "member"
  ],
  [
    "src/literal.js~literal#tont",
    "class/src/Literal.js~Literal.html#instance-method-toNT",
    "src/Literal.js~Literal#toNT",
    "method"
  ],
  [
    "src/literal.js~literal#tostring",
    "class/src/Literal.js~Literal.html#instance-method-toString",
    "src/Literal.js~Literal#toString",
    "method"
  ],
  [
    "src/literal.js~literal#value",
    "class/src/Literal.js~Literal.html#instance-get-value",
    "src/Literal.js~Literal#value",
    "member"
  ],
  [
    "src/literal.js~literal#valueof",
    "class/src/Literal.js~Literal.html#instance-method-valueOf",
    "src/Literal.js~Literal#valueOf",
    "method"
  ],
  [
    "src/literal.js~literal.fromnt",
    "class/src/Literal.js~Literal.html#static-method-fromNT",
    "src/Literal.js~Literal.fromNT",
    "method"
  ],
  [
    "src/literal.js~literal.isntliteral",
    "class/src/Literal.js~Literal.html#static-method-isNTLiteral",
    "src/Literal.js~Literal.isNTLiteral",
    "method"
  ],
  [
    "src/namednode.js",
    "file/src/NamedNode.js.html",
    "src/NamedNode.js",
    "file"
  ],
  [
    "src/namednode.js~namednode#constructor",
    "class/src/NamedNode.js~NamedNode.html#instance-constructor-constructor",
    "src/NamedNode.js~NamedNode#constructor",
    "method"
  ],
  [
    "src/namednode.js~namednode#equals",
    "class/src/NamedNode.js~NamedNode.html#instance-method-equals",
    "src/NamedNode.js~NamedNode#equals",
    "method"
  ],
  [
    "src/namednode.js~namednode#iri",
    "class/src/NamedNode.js~NamedNode.html#instance-get-iri",
    "src/NamedNode.js~NamedNode#iri",
    "member"
  ],
  [
    "src/namednode.js~namednode#tont",
    "class/src/NamedNode.js~NamedNode.html#instance-method-toNT",
    "src/NamedNode.js~NamedNode#toNT",
    "method"
  ],
  [
    "src/namednode.js~namednode#tostring",
    "class/src/NamedNode.js~NamedNode.html#instance-method-toString",
    "src/NamedNode.js~NamedNode#toString",
    "method"
  ],
  [
    "src/namednode.js~namednode#valueof",
    "class/src/NamedNode.js~NamedNode.html#instance-method-valueOf",
    "src/NamedNode.js~NamedNode#valueOf",
    "method"
  ],
  [
    "src/namednode.js~namednode.fromnt",
    "class/src/NamedNode.js~NamedNode.html#static-method-fromNT",
    "src/NamedNode.js~NamedNode.fromNT",
    "method"
  ],
  [
    "src/namednode.js~namednode.isntnamednode",
    "class/src/NamedNode.js~NamedNode.html#static-method-isNTNamedNode",
    "src/NamedNode.js~NamedNode.isNTNamedNode",
    "method"
  ],
  [
    "src/prefixmap.js",
    "file/src/PrefixMap.js.html",
    "src/PrefixMap.js",
    "file"
  ],
  [
    "src/prefixmap.js~prefixmap#[symbol.iterator]",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-[Symbol.iterator]",
    "src/PrefixMap.js~PrefixMap#[Symbol.iterator]",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#addall",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-addAll",
    "src/PrefixMap.js~PrefixMap#addAll",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#clone",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-clone",
    "src/PrefixMap.js~PrefixMap#clone",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#constructor",
    "class/src/PrefixMap.js~PrefixMap.html#instance-constructor-constructor",
    "src/PrefixMap.js~PrefixMap#constructor",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#entries",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-entries",
    "src/PrefixMap.js~PrefixMap#entries",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#hasnamespace",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-hasNamespace",
    "src/PrefixMap.js~PrefixMap#hasNamespace",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#hasprefix",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-hasPrefix",
    "src/PrefixMap.js~PrefixMap#hasPrefix",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#namespaces",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-namespaces",
    "src/PrefixMap.js~PrefixMap#namespaces",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#prefixes",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-prefixes",
    "src/PrefixMap.js~PrefixMap#prefixes",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#remove",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-remove",
    "src/PrefixMap.js~PrefixMap#remove",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#resolve",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-resolve",
    "src/PrefixMap.js~PrefixMap#resolve",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#set",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-set",
    "src/PrefixMap.js~PrefixMap#set",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#setdefault",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-setDefault",
    "src/PrefixMap.js~PrefixMap#setDefault",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#shrink",
    "class/src/PrefixMap.js~PrefixMap.html#instance-method-shrink",
    "src/PrefixMap.js~PrefixMap#shrink",
    "method"
  ],
  [
    "src/prefixmap.js~prefixmap#size",
    "class/src/PrefixMap.js~PrefixMap.html#instance-get-size",
    "src/PrefixMap.js~PrefixMap#size",
    "member"
  ],
  [
    "src/profile.js",
    "file/src/Profile.js.html",
    "src/Profile.js",
    "file"
  ],
  [
    "src/profile.js~profile#clone",
    "class/src/Profile.js~Profile.html#instance-method-clone",
    "src/Profile.js~Profile#clone",
    "method"
  ],
  [
    "src/profile.js~profile#constructor",
    "class/src/Profile.js~Profile.html#instance-constructor-constructor",
    "src/Profile.js~Profile#constructor",
    "method"
  ],
  [
    "src/profile.js~profile#importprofile",
    "class/src/Profile.js~Profile.html#instance-method-importProfile",
    "src/Profile.js~Profile#importProfile",
    "method"
  ],
  [
    "src/profile.js~profile#nodetostring",
    "class/src/Profile.js~Profile.html#instance-method-nodeToString",
    "src/Profile.js~Profile#nodeToString",
    "method"
  ],
  [
    "src/profile.js~profile#resolve",
    "class/src/Profile.js~Profile.html#instance-method-resolve",
    "src/Profile.js~Profile#resolve",
    "method"
  ],
  [
    "src/profile.js~profile#setdefaultprefix",
    "class/src/Profile.js~Profile.html#instance-method-setDefaultPrefix",
    "src/Profile.js~Profile#setDefaultPrefix",
    "method"
  ],
  [
    "src/profile.js~profile#setdefaultvocabulary",
    "class/src/Profile.js~Profile.html#instance-method-setDefaultVocabulary",
    "src/Profile.js~Profile#setDefaultVocabulary",
    "method"
  ],
  [
    "src/profile.js~profile#setprefix",
    "class/src/Profile.js~Profile.html#instance-method-setPrefix",
    "src/Profile.js~Profile#setPrefix",
    "method"
  ],
  [
    "src/profile.js~profile#setterm",
    "class/src/Profile.js~Profile.html#instance-method-setTerm",
    "src/Profile.js~Profile#setTerm",
    "method"
  ],
  [
    "src/rdfenvironment.js",
    "file/src/RDFEnvironment.js.html",
    "src/RDFEnvironment.js",
    "file"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#constructor",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-constructor-constructor",
    "src/RDFEnvironment.js~RDFEnvironment#constructor",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createaction",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createAction",
    "src/RDFEnvironment.js~RDFEnvironment#createAction",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createblanknode",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createBlankNode",
    "src/RDFEnvironment.js~RDFEnvironment#createBlankNode",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#creategraph",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createGraph",
    "src/RDFEnvironment.js~RDFEnvironment#createGraph",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createliteral",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createLiteral",
    "src/RDFEnvironment.js~RDFEnvironment#createLiteral",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createnamednode",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createNamedNode",
    "src/RDFEnvironment.js~RDFEnvironment#createNamedNode",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createprefixmap",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createPrefixMap",
    "src/RDFEnvironment.js~RDFEnvironment#createPrefixMap",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createprofile",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createProfile",
    "src/RDFEnvironment.js~RDFEnvironment#createProfile",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createtermmap",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createTermMap",
    "src/RDFEnvironment.js~RDFEnvironment#createTermMap",
    "method"
  ],
  [
    "src/rdfenvironment.js~rdfenvironment#createtriple",
    "class/src/RDFEnvironment.js~RDFEnvironment.html#instance-method-createTriple",
    "src/RDFEnvironment.js~RDFEnvironment#createTriple",
    "method"
  ],
  [
    "src/rdfnode.js",
    "file/src/RDFNode.js.html",
    "src/RDFNode.js",
    "file"
  ],
  [
    "src/rdfnode.js~rdfnode#constructor",
    "class/src/RDFNode.js~RDFNode.html#instance-constructor-constructor",
    "src/RDFNode.js~RDFNode#constructor",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#equals",
    "class/src/RDFNode.js~RDFNode.html#instance-method-equals",
    "src/RDFNode.js~RDFNode#equals",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#id",
    "class/src/RDFNode.js~RDFNode.html#instance-member-id",
    "src/RDFNode.js~RDFNode#id",
    "member"
  ],
  [
    "src/rdfnode.js~rdfnode#interfacename",
    "class/src/RDFNode.js~RDFNode.html#instance-member-interfaceName",
    "src/RDFNode.js~RDFNode#interfaceName",
    "member"
  ],
  [
    "src/rdfnode.js~rdfnode#isblanknode",
    "class/src/RDFNode.js~RDFNode.html#instance-method-isBlankNode",
    "src/RDFNode.js~RDFNode#isBlankNode",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#isliteral",
    "class/src/RDFNode.js~RDFNode.html#instance-method-isLiteral",
    "src/RDFNode.js~RDFNode#isLiteral",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#isnamednode",
    "class/src/RDFNode.js~RDFNode.html#instance-method-isNamedNode",
    "src/RDFNode.js~RDFNode#isNamedNode",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#nominalvalue",
    "class/src/RDFNode.js~RDFNode.html#instance-member-nominalValue",
    "src/RDFNode.js~RDFNode#nominalValue",
    "member"
  ],
  [
    "src/rdfnode.js~rdfnode#tont",
    "class/src/RDFNode.js~RDFNode.html#instance-method-toNT",
    "src/RDFNode.js~RDFNode#toNT",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#tostring",
    "class/src/RDFNode.js~RDFNode.html#instance-method-toString",
    "src/RDFNode.js~RDFNode#toString",
    "method"
  ],
  [
    "src/rdfnode.js~rdfnode#valueof",
    "class/src/RDFNode.js~RDFNode.html#instance-method-valueOf",
    "src/RDFNode.js~RDFNode#valueOf",
    "method"
  ],
  [
    "src/termmap.js",
    "file/src/TermMap.js.html",
    "src/TermMap.js",
    "file"
  ],
  [
    "src/termmap.js~termmap#[symbol.iterator]",
    "class/src/TermMap.js~TermMap.html#instance-method-[Symbol.iterator]",
    "src/TermMap.js~TermMap#[Symbol.iterator]",
    "method"
  ],
  [
    "src/termmap.js~termmap#addall",
    "class/src/TermMap.js~TermMap.html#instance-method-addAll",
    "src/TermMap.js~TermMap#addAll",
    "method"
  ],
  [
    "src/termmap.js~termmap#clone",
    "class/src/TermMap.js~TermMap.html#instance-method-clone",
    "src/TermMap.js~TermMap#clone",
    "method"
  ],
  [
    "src/termmap.js~termmap#constructor",
    "class/src/TermMap.js~TermMap.html#instance-constructor-constructor",
    "src/TermMap.js~TermMap#constructor",
    "method"
  ],
  [
    "src/termmap.js~termmap#entries",
    "class/src/TermMap.js~TermMap.html#instance-method-entries",
    "src/TermMap.js~TermMap#entries",
    "method"
  ],
  [
    "src/termmap.js~termmap#hasiri",
    "class/src/TermMap.js~TermMap.html#instance-method-hasIRI",
    "src/TermMap.js~TermMap#hasIRI",
    "method"
  ],
  [
    "src/termmap.js~termmap#hasterm",
    "class/src/TermMap.js~TermMap.html#instance-method-hasTerm",
    "src/TermMap.js~TermMap#hasTerm",
    "method"
  ],
  [
    "src/termmap.js~termmap#iris",
    "class/src/TermMap.js~TermMap.html#instance-method-iris",
    "src/TermMap.js~TermMap#iris",
    "method"
  ],
  [
    "src/termmap.js~termmap#remove",
    "class/src/TermMap.js~TermMap.html#instance-method-remove",
    "src/TermMap.js~TermMap#remove",
    "method"
  ],
  [
    "src/termmap.js~termmap#resolve",
    "class/src/TermMap.js~TermMap.html#instance-method-resolve",
    "src/TermMap.js~TermMap#resolve",
    "method"
  ],
  [
    "src/termmap.js~termmap#set",
    "class/src/TermMap.js~TermMap.html#instance-method-set",
    "src/TermMap.js~TermMap#set",
    "method"
  ],
  [
    "src/termmap.js~termmap#setdefault",
    "class/src/TermMap.js~TermMap.html#instance-method-setDefault",
    "src/TermMap.js~TermMap#setDefault",
    "method"
  ],
  [
    "src/termmap.js~termmap#shrink",
    "class/src/TermMap.js~TermMap.html#instance-method-shrink",
    "src/TermMap.js~TermMap#shrink",
    "method"
  ],
  [
    "src/termmap.js~termmap#size",
    "class/src/TermMap.js~TermMap.html#instance-get-size",
    "src/TermMap.js~TermMap#size",
    "member"
  ],
  [
    "src/termmap.js~termmap#terms",
    "class/src/TermMap.js~TermMap.html#instance-method-terms",
    "src/TermMap.js~TermMap#terms",
    "method"
  ],
  [
    "src/triple.js",
    "file/src/Triple.js.html",
    "src/Triple.js",
    "file"
  ],
  [
    "src/triple.js~triple#constructor",
    "class/src/Triple.js~Triple.html#instance-constructor-constructor",
    "src/Triple.js~Triple#constructor",
    "method"
  ],
  [
    "src/triple.js~triple#equals",
    "class/src/Triple.js~Triple.html#instance-method-equals",
    "src/Triple.js~Triple#equals",
    "method"
  ],
  [
    "src/triple.js~triple#id",
    "class/src/Triple.js~Triple.html#instance-member-id",
    "src/Triple.js~Triple#id",
    "member"
  ],
  [
    "src/triple.js~triple#object",
    "class/src/Triple.js~Triple.html#instance-member-object",
    "src/Triple.js~Triple#object",
    "member"
  ],
  [
    "src/triple.js~triple#predicate",
    "class/src/Triple.js~Triple.html#instance-member-predicate",
    "src/Triple.js~Triple#predicate",
    "member"
  ],
  [
    "src/triple.js~triple#subject",
    "class/src/Triple.js~Triple.html#instance-member-subject",
    "src/Triple.js~Triple#subject",
    "member"
  ],
  [
    "src/triple.js~triple#tostring",
    "class/src/Triple.js~Triple.html#instance-method-toString",
    "src/Triple.js~Triple#toString",
    "method"
  ],
  [
    "src/turtlereader.js",
    "file/src/TurtleReader.js.html",
    "src/TurtleReader.js",
    "file"
  ],
  [
    "src/turtlereader.js~turtlereader#constructor",
    "class/src/TurtleReader.js~TurtleReader.html#instance-constructor-constructor",
    "src/TurtleReader.js~TurtleReader#constructor",
    "method"
  ],
  [
    "src/turtlereader.js~turtlereader#isblank",
    "class/src/TurtleReader.js~TurtleReader.html#instance-method-isBlank",
    "src/TurtleReader.js~TurtleReader#isBlank",
    "method"
  ],
  [
    "src/turtlereader.js~turtlereader#isiri",
    "class/src/TurtleReader.js~TurtleReader.html#instance-method-isIRI",
    "src/TurtleReader.js~TurtleReader#isIRI",
    "method"
  ],
  [
    "src/turtlereader.js~turtlereader#isliteral",
    "class/src/TurtleReader.js~TurtleReader.html#instance-method-isLiteral",
    "src/TurtleReader.js~TurtleReader#isLiteral",
    "method"
  ],
  [
    "src/turtlereader.js~turtlereader#parse",
    "class/src/TurtleReader.js~TurtleReader.html#instance-method-parse",
    "src/TurtleReader.js~TurtleReader#parse",
    "method"
  ],
  [
    "src/turtlereader.js~turtlereader#parsen3entity",
    "class/src/TurtleReader.js~TurtleReader.html#instance-method-parseN3Entity",
    "src/TurtleReader.js~TurtleReader#parseN3Entity",
    "method"
  ],
  [
    "src/turtlewriter.js",
    "file/src/TurtleWriter.js.html",
    "src/TurtleWriter.js",
    "file"
  ],
  [
    "src/turtlewriter.js~turtlewriter#constructor",
    "class/src/TurtleWriter.js~TurtleWriter.html#instance-constructor-constructor",
    "src/TurtleWriter.js~TurtleWriter#constructor",
    "method"
  ],
  [
    "src/turtlewriter.js~turtlewriter#serialize",
    "class/src/TurtleWriter.js~TurtleWriter.html#instance-method-serialize",
    "src/TurtleWriter.js~TurtleWriter#serialize",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/n3/n3lexer.js",
    "file/src/n3/n3Lexer.js.html",
    "src/n3/n3Lexer.js",
    "file"
  ],
  [
    "src/n3/n3parser.js",
    "file/src/n3/n3Parser.js.html",
    "src/n3/n3Parser.js",
    "file"
  ],
  [
    "src/xmlschematypes.js",
    "file/src/xmlSchemaTypes.js.html",
    "src/xmlSchemaTypes.js",
    "file"
  ]
]